# Generated by Django 4.0 on 2022-02-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
